ARG NODE_VERSION=24

FROM node:${NODE_VERSION}-trixie-slim AS node

FROM ghcr.io/robgee86/licensed-action:v0

COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
RUN ln -s ../lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm && ln -s ../lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx
